Sankabinis/Controllers/LeaderController.cs
using Microsoft.AspNetCore.Mvc;
using Sankabinis.Data;
using Sankabinis.Models;
using System.Collections.Generic;
using System.Linq;

public class LeaderController : Controller
{

    private readonly SankabinisContext _context;

    public LeaderController(SankabinisContext context)
    {
        _context = context;
    }

    // Action method to get leaderboard data
    public IActionResult GetLeaderboardData()
    {
        var leaders = GetLeaderTable();
        return Json(leaders); // Return leaders as JSON
    }

    private List<User> GetLeaderTable()
    {
        // Fetch top 10 users based on Elo
        var leaders = _context.Users.OrderByDescending(u => u.Elo).Take(10).ToList();
        return leaders;
    }


}

Sankabinis/Views/Leaders/LeaderPage.cshtml
@model List<Sankabinis.Models.User>

<!DOCTYPE html>
<html>
<head>
    <title>Leader Page</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Leaderboard</h1>

    <table id="leaderboard-table">
        <tr>
            <th>Vardas ir Pavardė</th>
            <th>Elo</th>
        </tr>
    </table>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("GetLeaderboardData", "Leader")',
                type: 'GET',
                success: function (data) {
                    $.each(data, function (index, leader) {
                        $('#leaderboard-table').append('<tr><td>' + leader.vardas_pavarde + '</td><td>' + leader.elo + '</td></tr>');
                    });
                },
                error: function () {
                    console.error('Error fetching leaderboard data.');
                }
            });
        });
    </script>

</body>
</html>