Sankabinis/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sankabinis.Data;
using Sankabinis.Models;

namespace Sankabinis.Controllers
{
    public class CarsController : Controller
    {
        private readonly SankabinisContext _context;

        public CarsController(SankabinisContext context)
        {
            _context = context;
        }

        // GET: CarsPage
        public async Task<IActionResult> Index()
        {
            var loggedInUserId = HttpContext.Session.GetInt32("UserId");
            if (loggedInUserId == null)
            {
                return RedirectToPage("/Home/NavigateToSignInPage");
                //return RedirectToAction("../Home/NavigateToSignInPage"); // Or any other appropriate action
            }

            var userCars = _context.Car
                .Where(car => car.Fk_Naudotojasid_Naudotojas == loggedInUserId.Value)
                .ToListAsync();

            return View(await userCars);
        }

        // GET: CarsPage/Details/5
        // GET: CarsPage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loggedInUserId = HttpContext.Session.GetInt32("UserId");
            if (loggedInUserId == null)
            {
                return RedirectToAction("Login"); // Or any other appropriate action
            }

            var automobilis = await _context.Car
                .FirstOrDefaultAsync(m => m.Id_Automobilis == id && m.Fk_Naudotojasid_Naudotojas == loggedInUserId.Value);

            if (automobilis == null)
            {
                return NotFound();
            }

            return View(automobilis);
        }


        // GET: CarsPage/Create
        public IActionResult Create()
        {
            ViewBag.PavaruDezeOptions = Enum.GetValues(typeof(PavaruDeze))
                .Cast<PavaruDeze>()
                .Select(d => new SelectListItem
                {
                    Text = d.ToString(),
                    Value = ((int)d).ToString()
                }).ToList();
            // Populate KuroTipas select list
            ViewBag.KuroTipasOptions = Enum.GetValues(typeof(KuroTipas))
                .Cast<KuroTipas>()
                .Select(kt => new SelectListItem
                {
                    Text = kt.ToString(),
                    Value = ((int)kt).ToString()
                }).ToList();

            // Populate Kebulas select list
            ViewBag.KebulasOptions = Enum.GetValues(typeof(Kebulas))
                .Cast<Kebulas>()
                .Select(k => new SelectListItem
                {
                    Text = k.ToString(),
                    Value = ((int)k).ToString()
                }).ToList();

            // Populate Klase select list
            ViewBag.KlaseOptions = Enum.GetValues(typeof(AutomobilioKlase))
                .Cast<AutomobilioKlase>()
                .Select(cl => new SelectListItem
                {
                    Text = cl.ToString(),
                    Value = ((int)cl).ToString()
                }).ToList();

            return View();
        }

        // POST: CarsPage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Automobilis,Modelis,Marke,Numeris,Galingumas,Spalva,Rida,Pagaminimo_data,Svoris,Kuro_tipas,Pavaru_deze,Kebulas")] Car automobilis)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the logged in user's ID from session
                var loggedInUserId = HttpContext.Session.GetInt32("UserId");

                // Set the user ID to the car object
                automobilis.Fk_Naudotojasid_Naudotojas = loggedInUserId.Value;

                _context.Add(automobilis);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Reload dropdown data for re-displaying form if validation fails
            LoadSelectLists();
            return View(automobilis);
        }

        private bool ValidateData(Car car)
        {
            return true;
        }
        private double PowerWeight(double svoris, int galia)
        {
            return (double)galia / svoris;
        }

        private int Klase(double pw)
        {
            if (pw < 0.05)
                return 1;
            else if (pw < 0.1 && pw >= 0.05)
                return 2;
            else if (pw < 0.2 && pw >= 0.1)
                return 3;
            else
                return 4;
        }
        // GET: CarsPage/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var automobilis = await _context.Car.FindAsync(id);
            if (automobilis == null)
            {
                return NotFound();
            }

            ViewBag.KuroTipasSelectList = new SelectList(Enum.GetValues(typeof(KuroTipas)));
            ViewBag.PavaruDezeSelectList = new SelectList(Enum.GetValues(typeof(PavaruDeze)));
            ViewBag.KebulasSelectList = new SelectList(Enum.GetValues(typeof(Kebulas)));
            ViewBag.KlaseSelectList = new SelectList(Enum.GetValues(typeof(AutomobilioKlase)));

            return View(automobilis);
        }

        // POST: CarsPage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Automobilis,Modelis,Marke,Numeris,Galingumas,Spalva,Rida,Pagaminimo_data,Svoris,Kuro_tipas,Pavaru_deze,Kebulas,Fk_Naudotojasid_Naudotojas")] Car automobilis)
        {
            if (id != automobilis.Id_Automobilis)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    automobilis.Klase = CalculateClass(automobilis.Svoris, automobilis.Galingumas);
                    _context.Update(automobilis);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutomobilisExists(automobilis.Id_Automobilis))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            LoadSelectLists();
            return View(automobilis);
        }
        private void LoadSelectLists()
        {
            ViewBag.KuroTipasOptions = new SelectList(Enum.GetValues(typeof(KuroTipas)), "Value", "Text");
            ViewBag.PavaruDezeOptions = new SelectList(Enum.GetValues(typeof(PavaruDeze)), "Value", "Text");
            ViewBag.KebulasOptions = new SelectList(Enum.GetValues(typeof(Kebulas)), "Value", "Text");
            ViewBag.KlaseOptions = new SelectList(Enum.GetValues(typeof(AutomobilioKlase)), "Value", "Text");
        }

        private AutomobilioKlase CalculateClass(double svoris, int galingumas)
        {
            double pw = PowerWeight(svoris, galingumas);
            return (AutomobilioKlase)Klase(pw);
        }


        // GET: CarsPage/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var automobilis = await _context.Car
                .FirstOrDefaultAsync(m => m.Id_Automobilis == id);
            if (automobilis == null)
            {
                return NotFound();
            }

            return View(automobilis);
        }

        // POST: CarsPage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var automobilis = await _context.Car.FindAsync(id);
            if (automobilis != null)
            {
                _context.Car.Remove(automobilis);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutomobilisExists(int id)
        {
            return _context.Car.Any(e => e.Id_Automobilis == id);
        }
    }
}

Sankabinis/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Sankabinis.Controllers;
using Sankabinis.Data;
using Sankabinis.Models;
using System.ComponentModel.DataAnnotations;

public class UserController : Controller
{
    private readonly GoogleApiController _googleApiController;
    private readonly SankabinisContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public UserController(GoogleApiController googleApiController, SankabinisContext context, IWebHostEnvironment webHostEnvironment)
    {
        _googleApiController = googleApiController;
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }

    [HttpPost]
    [ValidateAntiForgeryToken]

    public IActionResult RegistrationPage()
    {
        return View();
    }
    public IActionResult ValidateRegistration(User user)
    {
        if (string.IsNullOrEmpty(user.Slapyvardis))
        {
            return View("RegistrationPage", user);
        }
        if (string.IsNullOrEmpty(user.Slaptazodis))
        {
            return View("RegistrationPage", user);
        }

        if (_context.Users.Any(u => u.Slapyvardis == user.Slapyvardis))
        {
            ModelState.AddModelError("Slapyvardis", "This slapyvardis is already taken.");
            return View("RegistrationPage", user);
        }

        CreateAccount(user);
        return NavigateToSignInPage(user);
    }
    private IActionResult CreateAccount(User user)
    {
        user.Paskyros_sukurimo_data = DateTime.Now;
        user.Busena = "Aktyvi";
        user.Elo = 0;
        user.Lenktyniu_skaicius = 0;
        user.Laimėta_lenktyniu = 0;
        user.Pralaimėta_lenktyniu = 0;
        user.Pasitikimo_taskai = 200;
        user.Paskutinio_prisijungimo_data = DateTime.Now;
        user.Suspeduotos_busenos_skaicius = 0;
        user.El_pastas = "";
        user.Vardas_pavarde = "";
        user.Gimimo_data = DateTime.Now;
        user.Lytis = "";
        user.Patirtis = "";
        user.Svoris = 0;
        user.Level = 0;

        _context.Users.Add(user);
        _context.SaveChanges();

        return Ok();
    }
    public IActionResult NavigateToSignInPage(User user)
    {
        return View("SignInPage", user);
    }

    public IActionResult ValidateSignIn(User user)
    {
        if (string.IsNullOrEmpty(user.Slapyvardis))
        {
            return View("SignInPage", user);
        }
        if (string.IsNullOrEmpty(user.Slaptazodis))
        {
            return View("SignInPage", user);
        }
        var existingUser = _context.Users.FirstOrDefault(u => u.Slapyvardis == user.Slapyvardis && u.Slaptazodis == user.Slaptazodis);
        if (existingUser == null)
        {
            ModelState.AddModelError("Slaptazodis", "Invalid username or password.");
            return View("SignInPage", user);
        }

        SignIn(user, existingUser);
        return View("~/Views/Home/Index.cshtml");
    }

    public IActionResult SignIn(User user, User existingUser)
    {
        if (string.IsNullOrEmpty(existingUser.Lytis))
        {
            HttpContext.Session.SetInt32("UserId", existingUser.Id_Naudotojas);
        }
        else
        {
            HttpContext.Session.SetString("Username", user.Slapyvardis);
            HttpContext.Session.SetInt32("UserId", existingUser.Id_Naudotojas);
            HttpContext.Session.SetInt32("UserLevel", existingUser.Level);
        }
        return Ok();    
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
    }

    public IActionResult ValidateData(User user, string cityPavadinimas)
    {
        if (string.IsNullOrEmpty(user.Vardas_pavarde) ||
            string.IsNullOrEmpty(user.El_pastas) ||
            string.IsNullOrEmpty(user.Patirtis) ||
            string.IsNullOrEmpty(cityPavadinimas) ||
            user.Gimimo_data == null)
        {
            ModelState.AddModelError(string.Empty, "Please fill in all required fields.");
            Console.WriteLine("neveikia0");
            return View("ProfileCreationPage", user);
        }

        if (!new EmailAddressAttribute().IsValid(user.El_pastas))
        {
            ModelState.AddModelError("El_pastas", "Please enter a valid email address.");
            Console.WriteLine("neveikia1");
            return View("ProfileCreationPage", user);
        }

        if (user.Svoris <= 0)
        {
            ModelState.AddModelError("Svoris", "Please enter a valid weight.");
            return View("ProfileCreationPage", user);
        }

        var today = DateTime.Today;
        var age = today.Year - user.Gimimo_data.Year;
        if (user.Gimimo_data.Date > today.AddYears(-age)) age--;
        if (age > 120)
        {
            ModelState.AddModelError("Gimimo_data", "Please fill in date.");
            return View("ProfileCreationPage", user);
        }

        var loggedInUserId = HttpContext.Session.GetInt32("UserId");
        var loggedInUser = _context.Users.FirstOrDefault(u => u.Id_Naudotojas == loggedInUserId);

        var cityController = new CityController(_googleApiController, _context, _webHostEnvironment);
        cityController.CheckIfExists(cityPavadinimas);

        loggedInUser.Vardas_pavarde = user.Vardas_pavarde;
        loggedInUser.El_pastas = user.El_pastas;
        loggedInUser.Patirtis = user.Patirtis;
        loggedInUser.Svoris = user.Svoris;
        loggedInUser.Gimimo_data = user.Gimimo_data;
        loggedInUser.Lytis = user.Lytis;

        var city = _context.City.FirstOrDefault(c => c.Pavadinimas == cityPavadinimas);
        if (city != null)
        {
            loggedInUser.CityId = city.Id_Miestas;
        }
        _context.SaveChanges();
        HttpContext.Session.SetString("Username", loggedInUser.Slapyvardis);
        HttpContext.Session.SetInt32("UserLevel", loggedInUser.Level);

        return RedirectToAction("Index", "Home");
    }

    public IActionResult ShowProfileData()
    {
        var loggedInUserId = HttpContext.Session.GetInt32("UserId");
        var loggedInUserLevel = HttpContext.Session.GetInt32("UserLevel");
        var user = _context.Users.FirstOrDefault(u => u.Id_Naudotojas == loggedInUserId);
        return Json(user);
    }



}

Sankabinis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sankabinis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sankabinis.styles.css" asp-append-version="true" />
</head>
@{
    var username = Context.Session.GetString("Username");
    var loggedInUserId = Context.Session.GetInt32("UserId");
    var loggedInUserLevel = Context.Session.GetInt32("UserLevel");
}
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sankabinis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav">
                        @if (loggedInUserId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToRegistrationPage">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToSignInPage">Login</a>
                            </li>
                        }
                        else if (string.IsNullOrEmpty(username)) //Cia tipo jeigu neturi profilio susikures tai reikia kad susikurtu pirma ir tik tada rodys likusius dal;ykus svetaines
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToProfileCreationPage">@username</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToProfileCreationPage">Create Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToRacePage">Race</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">My Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToLeaderPage">Leaderboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Achievements" asp-action="Index">Achievements</a>
                            </li>
                //Testavimui bet galimai ir velesniam naudojimui
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToUserRacesPage" asp-route-userId="@loggedInUserId">My Races</a>
                            </li>
                //Testavimui
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToProfilePage">Profile</a>
                            </li>
                            if(Context.Session.GetInt32("UserLevel") == 1)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NavigateToAppealListPage">Appeals</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sankabinis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>